apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: karsajobs-ui
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        app: karsajobs-ui
        type: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: ghcr.io/footgraph/a433-microservices/karsajobs-ui:latest
        ports:
          - containerPort: 8000