apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: karsajobs-ui
    type: frontend

spec:
  ports:  
  - protocol: TCP
    port: 8000
  selector:
    app: karsajobs-ui
    type: frontend