apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
    type: backend

spec:
  selector:
    matchLabels:
      app: mongo
      type: backend

  serviceName: mongo-service
  replicas: 1
  minReadySeconds: 10

  template:
    metadata:
      labels:
        app: mongo
        type: backend
        
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: mongo:latest
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-secret
              mountPath: /etc/mongo-credentials
            - name: mongo-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc-claim
        - name: mongo-secret
          secret:
            secretName: mongo-secret
        - name: mongo-config
          configMap:
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongo.conf