apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo
    type: backend
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
    type: backend
  clusterIP: None
